# -*- coding: utf-8 -*-
"""01_setup_infra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nW-gIgspZXUJdMRpB5KvRKGQ6Rb5XvHb
"""

from google.colab import drive
drive.mount('/content/drive')

import os

# Define o caminho base no seu Drive
base_path = '/content/drive/MyDrive/E-commerce_Insight_Pipeline'

folders = [
    f'{base_path}/scripts',
    f'{base_path}/data',
    f'{base_path}/dbt_ecommerce',
    f'{base_path}/dbt_ecommerce/models'
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)
    print(f"Pasta criada: {folder}")

# Ferramentas para Scraping, Banco de Dados e Transformação
!pip install requests beautifulsoup4 duckdb pandas dbt-duckdb